// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6TriuE9n464IzOeoFPr0kp0Nw2vWWrig',
    appId: '1:156040018112:web:26be6a521d43f6f9d31525',
    messagingSenderId: '156040018112',
    projectId: 'projemanage-76b93',
    authDomain: 'projemanage-76b93.firebaseapp.com',
    storageBucket: 'projemanage-76b93.firebasestorage.app',
    measurementId: 'G-40E4LFK4YD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPrH-LtgATevA7TwCgM8Y0oN7n2xTHMB8',
    appId: '1:156040018112:android:973d31fa57d7d27fd31525',
    messagingSenderId: '156040018112',
    projectId: 'projemanage-76b93',
    storageBucket: 'projemanage-76b93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgiZCJTtYkVAey69jPpFTdUheDLVu6Wnk',
    appId: '1:156040018112:ios:a6218d3ac4a36996d31525',
    messagingSenderId: '156040018112',
    projectId: 'projemanage-76b93',
    storageBucket: 'projemanage-76b93.firebasestorage.app',
    iosBundleId: 'com.example.projemanage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgiZCJTtYkVAey69jPpFTdUheDLVu6Wnk',
    appId: '1:156040018112:ios:a6218d3ac4a36996d31525',
    messagingSenderId: '156040018112',
    projectId: 'projemanage-76b93',
    storageBucket: 'projemanage-76b93.firebasestorage.app',
    iosBundleId: 'com.example.projemanage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6TriuE9n464IzOeoFPr0kp0Nw2vWWrig',
    appId: '1:156040018112:web:60b1796e390664f9d31525',
    messagingSenderId: '156040018112',
    projectId: 'projemanage-76b93',
    authDomain: 'projemanage-76b93.firebaseapp.com',
    storageBucket: 'projemanage-76b93.firebasestorage.app',
    measurementId: 'G-Y2X4JZ26D6',
  );

}